#开发环境配置
server:
  port: 8084

spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/db_shop?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


  # redis 配置
  data:
    redis:
      host: localhost
      password: redis
      port: 6379
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms


mybatis:
  mapper-locations: classpath:mapper/*.xml



# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: acbdexghijxlmnopxrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 1440
